#!/bin/bash

cp -r /usr/share/huayra-postinstall-pci/alumno/.config/* /home/alumno/.config
cp -r /usr/share/huayra-postinstall-pci/alumno/.local/* /home/alumno/.local
cp -r /usr/share/huayra-postinstall-pci/alumno/.config/* /etc/skel/.config
cp -r /usr/share/huayra-postinstall-pci/alumno/.local/* /etc/skel/.local