#!/bin/bash

echo 'KERNEL=="sda2", ENV{UDISKS_PRESENTATION_HIDE}=1" 
KERNEL=="sda5", ENV{UDISKS_PRESENTATION_HIDE}=1"' >> /etc/udev/rules.d/99-hide-disks.rules

echo "Escondiendo particiones de Windows y Recuperación"

