#!/bin/bash

zenity --info --text "Por favor, busque e instale las actualizaciones disponibles. 
A través del menú, en Herramientas del sistema -> Actualizaciones de software 
Desde una consola, ejecute: 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade"
