#!/bin/bash

if [ ! -f /etc/udev/rules.d/99-hide-disks.rules ]; then
        touch /etc/udev/rules.d/99-hide-disks.rules
fi

grep 'sda2' /etc/udev/rules.d/99-hide-disks.rules > /dev/null
if [ ! $? -eq 0 ]; then
    echo 'KERNEL=="sda2", ENV{UDISKS_PRESENTATION_HIDE}=1"' >> /etc/udev/rules.d/99-hide-disks.rules
fi

grep 'sda5' /etc/udev/rules.d/99-hide-disks.rules > /dev/null
if [ ! $? -eq 0 ]; then
    echo 'KERNEL=="sda5", ENV{UDISKS_PRESENTATION_HIDE}=1"' >> /etc/udev/rules.d/99-hide-disks.rules
fi

echo "Escondiendo particiones de Windows y Recuperación"

