.TH HUAYRA-POSTINSTALL-PCI "1" "April 2015" "huayra-postinstall-pci" "User Commands"
.SH NAME
huayra-postinstall-pci \- Configura una instalación de Huayra
.SH SYNOPSIS
.B huayra-postinstall-pci
[\fI-r\fR] [\fI-t\fR]
.SH DESCRIPTION
Ejecuta una serie de scrips para configurar Hauyra recién instalado
con los datos de la imágen de disco original de fábrica.
.LP
.SH OPTIONS
.TP
\fB\-r\fR
(modo RUN) Cuando se ejecuta el comando con éste parámtro, todas las acciones que 
modifiquen los datos del disco, serán aplicadas.
.TP
\fB\-t\fR
(modo TEST) No se aplican las modificaciones a la información. Útil para probar
antes de romper todo.
.SH AUTHORS
.B huayra-postinstall-pci
was written by Huayra Developers <http://huayra.conectarigualdad.gob.ar/>.
.P
This manual page was written by Fernando Toledo <ragnarok@docksud.com.ar>
for the Huayra project (but may be used by others).
